import { DigestSource } from './types';

// AI Builders - Follow builders, not influencers
export const builderSources: DigestSource[] = [
  {
    id: 'kevin-weil',
    name: 'Kevin Weil',
    nameZh: 'Kevin Weil',
    url: 'https://x.com/kevinweil',
    type: 'twitter',
    category: 'builder_insights',
    description: 'OpenAI Chief Product Officer',
    descriptionZh: 'OpenAI产品负责人',
  },
  {
    id: 'christopher-petregal',
    name: 'Christopher Petregal',
    nameZh: 'Christopher Petregal',
    url: 'https://x.com/cjpedregal',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Granola Founder',
    descriptionZh: 'Granola创始人',
  },
  {
    id: 'nan-yu',
    name: 'Nan Yu',
    nameZh: 'Nan Yu',
    url: 'https://x.com/thenanyu',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Linear Head of Product',
    descriptionZh: 'Linear产品负责人',
  },
  {
    id: 'raiza-martin',
    name: 'Raiza Martin',
    nameZh: 'Raiza Martin',
    url: 'https://x.com/raizamrtn',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Former Notebook LM Product Lead',
    descriptionZh: '前Notebook LM产品负责人',
  },
  {
    id: 'josh-woodward',
    name: 'Josh Woodward',
    nameZh: 'Josh Woodward',
    url: 'https://x.com/joshwoodward',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Google Labs and Gemini Lead',
    descriptionZh: 'Google Labs和Gemini负责人',
  },
  {
    id: 'amanda-askell',
    name: 'Amanda Askell',
    nameZh: 'Amanda Askell',
    url: 'https://x.com/AmandaAskell',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Anthropic Claude Character Lead',
    descriptionZh: 'Anthropic的Claude性格负责人',
  },
  {
    id: 'dario-amodei',
    name: 'Dario Amodei',
    nameZh: 'Dario Amodei',
    url: 'https://x.com/DarioAmodei',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Anthropic Co-founder & CEO',
    descriptionZh: 'Anthropic联合创始人 & CEO',
  },
  {
    id: 'demis-hassabis',
    name: 'Demis Hassabis',
    nameZh: 'Demis Hassabis',
    url: 'https://x.com/demishassabis',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Google DeepMind Co-founder & CEO',
    descriptionZh: 'Google DeepMind联合创始人 & CEO',
  },
  {
    id: 'ilya-sutskever',
    name: 'Ilya Sutskever',
    nameZh: 'Ilya Sutskever',
    url: 'https://x.com/ilyasut',
    type: 'twitter',
    category: 'builder_insights',
    description: 'SSI Co-founder, OpenAI Co-founder',
    descriptionZh: 'Safe Superintelligence联合创始人，OpenAI联合创始人',
  },
  {
    id: 'andrej-karpathy',
    name: 'Andrej Karpathy',
    nameZh: 'Andrej Karpathy',
    url: 'https://x.com/karpathy',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Eureka Labs Founder, Former OpenAI/Tesla',
    descriptionZh: 'Eureka Labs创始人、前OpenAI/Tesla',
  },
  {
    id: 'mira-murati',
    name: 'Mira Murati',
    nameZh: 'Mira Murati',
    url: 'https://x.com/miramurati',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Thinking Machines Founder, Former OpenAI CTO',
    descriptionZh: '前OpenAI CTO，现创办Thinking Machines',
  },
  {
    id: 'greg-brockman',
    name: 'Greg Brockman',
    nameZh: 'Greg Brockman',
    url: 'https://x.com/gdb',
    type: 'twitter',
    category: 'builder_insights',
    description: 'OpenAI Co-founder',
    descriptionZh: 'OpenAI联合创始人',
  },
  {
    id: 'mustafa-suleyman',
    name: 'Mustafa Suleyman',
    nameZh: 'Mustafa Suleyman',
    url: 'https://x.com/mustafasuleyman',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Microsoft AI CEO, DeepMind Co-founder',
    descriptionZh: '微软AI CEO、DeepMind联合创始人',
  },
  {
    id: 'lilian-weng',
    name: 'Lilian Weng',
    nameZh: 'Lilian Weng',
    url: 'https://x.com/lilianweng',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Thinking Machines Co-founder, Former OpenAI Research Lead',
    descriptionZh: 'Thinking Machines联合创始人，前OpenAI研究领导',
  },
  {
    id: 'logan-kilpatrick',
    name: 'Logan Kilpatrick',
    nameZh: 'Logan Kilpatrick',
    url: 'https://x.com/OfficialLoganK',
    type: 'twitter',
    category: 'builder_insights',
    description: 'Google Gemini Developer Ecosystem',
    descriptionZh: 'Google（Gemini）开发者生态公共面孔',
  },
];

// AI Blog Sources
export const blogSources: DigestSource[] = [
  {
    id: 'ai-daily-brief',
    name: 'The AI Daily Brief',
    nameZh: 'AI每日简报',
    url: 'https://www.youtube.com/@AIDailyBrief',
    type: 'youtube',
    category: 'blog_articles',
    description: 'Daily AI news and analysis',
    descriptionZh: 'AI每日新闻和分析',
  },
  {
    id: 'unsupervised-learning',
    name: 'Unsupervised Learning',
    nameZh: 'Unsupervised Learning',
    url: 'https://newsletter.danielmiessler.com/',
    type: 'blog',
    category: 'blog_articles',
    description: 'Redpoint Capital AI Newsletter',
    descriptionZh: 'Redpoint Capital AI通讯',
  },
  {
    id: 'training-data',
    name: 'Training Data',
    nameZh: 'Training Data',
    url: 'https://www.blog.trainindata.com/',
    type: 'blog',
    category: 'blog_articles',
    description: 'Sequoia Capital AI Blog',
    descriptionZh: 'Sequoia Capital AI博客',
  },
  {
    id: 'no-priors',
    name: 'No Priors',
    nameZh: 'No Priors',
    url: 'https://x.com/NoPriorsPod',
    type: 'podcast',
    category: 'blog_articles',
    description: 'AI Podcast',
    descriptionZh: 'AI播客',
  },
  {
    id: 'latent-space',
    name: 'Latent Space',
    nameZh: 'Latent Space',
    url: 'https://www.latentspace.blog/',
    type: 'blog',
    category: 'blog_articles',
    description: 'AI/ML Technical Blog',
    descriptionZh: 'AI/ML技术博客',
  },
];

// Interview/Podcast Sources
export const podcastSources: DigestSource[] = [
  {
    id: 'lennys-podcast',
    name: "Lenny's Podcast",
    nameZh: "Lenny's Podcast",
    url: 'https://www.youtube.com/@LennysPodcast',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'Product and Growth Podcast',
    descriptionZh: '产品和增长播客',
  },
  {
    id: 'peter-yang',
    name: 'Peter Yang',
    nameZh: 'Peter Yang',
    url: 'https://www.youtube.com/@PeterYangYT',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'Product Management Content',
    descriptionZh: '产品管理内容',
  },
  {
    id: 'minus-one',
    name: 'Minus One',
    nameZh: 'Minus One',
    url: 'https://minusone.southparkcommons.com/',
    type: 'podcast',
    category: 'podcast_interviews',
    description: 'South Park Commons Podcast',
    descriptionZh: 'South Park Commons播客',
  },
  {
    id: 'dwarkesh-patel',
    name: 'Dwarkesh Podcast',
    nameZh: 'Dwarkesh Podcast',
    url: 'https://www.youtube.com/@DwarkeshPatel',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'Deep Dive Interviews',
    descriptionZh: '深度访谈',
  },
  {
    id: 'lex-fridman',
    name: 'Lex Fridman',
    nameZh: 'Lex Fridman',
    url: 'https://x.com/lexfridman',
    type: 'twitter',
    category: 'podcast_interviews',
    description: 'AI Researcher and Podcaster',
    descriptionZh: 'AI研究者和播客主持人',
  },
  {
    id: 'cognitive-revolution',
    name: 'The Cognitive Revolution',
    nameZh: 'The Cognitive Revolution',
    url: 'https://www.youtube.com/@CognitiveRevolutionPodcast',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'AI Deep Dives',
    descriptionZh: 'AI深度探讨',
  },
  {
    id: 'tbpn',
    name: 'TBPN',
    nameZh: 'TBPN',
    url: 'https://www.youtube.com/@TBPNLive',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'Tech Business Podcast',
    descriptionZh: '科技商业播客',
  },
  {
    id: 'all-in',
    name: 'All In Podcast',
    nameZh: 'All In Podcast',
    url: 'https://www.youtube.com/@allin',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'Tech and Investment Podcast',
    descriptionZh: '科技和投资播客',
  },
  {
    id: 'in-good-company',
    name: 'In Good Company',
    nameZh: 'In Good Company',
    url: 'https://www.youtube.com/playlist?list=PLzYp5zh-CrBUX_4WnPCO1jj5v6jMuQjKe',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'Business Interviews',
    descriptionZh: '商业访谈',
  },
  {
    id: 'bg2-pod',
    name: 'BG2 Pod',
    nameZh: 'BG2 Pod',
    url: 'https://www.youtube.com/@Bg2Pod',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'Tech Podcast',
    descriptionZh: '科技播客',
  },
  {
    id: 'lexie-podcast',
    name: 'Lexie Podcast',
    nameZh: 'Lexie Podcast',
    url: 'https://www.youtube.com/playlist?list=PLCdq-zMaAiEeMuJixzFJVrBTs4JtI1j30',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'Tech Interviews',
    descriptionZh: '科技访谈',
  },
  {
    id: '20vc',
    name: '20 VC',
    nameZh: '20 VC',
    url: 'https://www.youtube.com/@20VC',
    type: 'youtube',
    category: 'podcast_interviews',
    description: 'Venture Capital Podcast',
    descriptionZh: '风险投资播客',
  },
];

// News Website Sources
export const newsSources: DigestSource[] = [
  {
    id: 'aihot-today',
    name: 'AI Hot Today',
    nameZh: 'AI Hot Today',
    url: 'https://aihot.today/',
    type: 'website',
    category: 'news',
    description: 'Latest AI news in 24 hours',
    descriptionZh: '24小时内最新资讯',
  },
  {
    id: 'aibase-cn',
    name: 'AIbase',
    nameZh: 'AIbase',
    url: 'https://www.aibase.cn/',
    type: 'website',
    category: 'news',
    description: 'Comprehensive AI News Platform',
    descriptionZh: '内容全面的AI资讯网站',
  },
  {
    id: 'xueqiu',
    name: 'Xueqiu',
    nameZh: '雪球',
    url: 'https://xueqiu.com/',
    type: 'website',
    category: 'news',
    description: 'Investment and Tech News',
    descriptionZh: '投资和科技新闻',
  },
];

// Core AI Model Company Sources
export const companySources: DigestSource[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    nameZh: 'OpenAI',
    url: 'https://x.com/OpenAI',
    type: 'twitter',
    category: 'product_updates',
    description: 'OpenAI Official',
    descriptionZh: 'OpenAI官方',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    nameZh: 'Anthropic',
    url: 'https://x.com/AnthropicAI',
    type: 'twitter',
    category: 'product_updates',
    description: 'Anthropic Official',
    descriptionZh: 'Anthropic官方',
  },
  {
    id: 'xai',
    name: 'xAI',
    nameZh: 'xAI',
    url: 'https://x.com/xai',
    type: 'twitter',
    category: 'product_updates',
    description: 'xAI Official',
    descriptionZh: 'xAI官方',
  },
  {
    id: 'google-deepmind',
    name: 'Google DeepMind',
    nameZh: 'Google DeepMind',
    url: 'https://x.com/GoogleDeepMind',
    type: 'twitter',
    category: 'product_updates',
    description: 'Google DeepMind Official',
    descriptionZh: 'Google DeepMind官方',
  },
  {
    id: 'meta-ai',
    name: 'Meta AI',
    nameZh: 'Meta AI',
    url: 'https://x.com/AIatMeta',
    type: 'twitter',
    category: 'product_updates',
    description: 'Meta AI Official',
    descriptionZh: 'Meta AI官方',
  },
  {
    id: 'alibaba-qwen',
    name: 'Alibaba Qwen',
    nameZh: '阿里通义千问',
    url: 'https://x.com/Alibaba_Qwen',
    type: 'twitter',
    category: 'product_updates',
    description: 'Alibaba Qwen Official',
    descriptionZh: '阿里通义千问官方',
  },
  {
    id: 'tencent-hunyuan',
    name: 'Tencent Hunyuan',
    nameZh: '腾讯混元',
    url: 'https://x.com/TencentHunyuan',
    type: 'twitter',
    category: 'product_updates',
    description: 'Tencent Hunyuan Official',
    descriptionZh: '腾讯混元官方',
  },
  {
    id: 'moonshot-ai',
    name: 'Moonshot AI',
    nameZh: '月之暗面',
    url: 'https://x.com/Kimi_Moonshot',
    type: 'twitter',
    category: 'product_updates',
    description: 'Moonshot AI (Kimi) Official',
    descriptionZh: '月之暗面（Kimi）官方',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    nameZh: 'MiniMax',
    url: 'https://x.com/MiniMax__AI',
    type: 'twitter',
    category: 'product_updates',
    description: 'MiniMax Official',
    descriptionZh: 'MiniMax官方',
  },
  {
    id: 'huawei-pangu',
    name: 'Huawei PanGu',
    nameZh: '华为盘古',
    url: 'https://x.com/Huawei',
    type: 'twitter',
    category: 'product_updates',
    description: 'Huawei Official',
    descriptionZh: '华为官方',
  },
];

// All sources combined
export const allSources: DigestSource[] = [
  ...builderSources,
  ...blogSources,
  ...podcastSources,
  ...newsSources,
  ...companySources,
];

// Helper functions
export const getSourceById = (id: string): DigestSource | undefined =>
  allSources.find((s) => s.id === id);

export const getSourcesByCategory = (category: string): DigestSource[] =>
  allSources.filter((s) => s.category === category);

export const getSourcesByType = (type: string): DigestSource[] =>
  allSources.filter((s) => s.type === type);

// Category display info
export const categoryInfo: Record<string, { name: string; nameZh: string; icon: string }> = {
  builder_insights: {
    name: 'Builder Insights',
    nameZh: 'AI大V观点',
    icon: 'Users',
  },
  product_updates: {
    name: 'Product Updates',
    nameZh: '产品更新',
    icon: 'Rocket',
  },
  blog_articles: {
    name: 'Blog Articles',
    nameZh: '博客文章',
    icon: 'FileText',
  },
  podcast_interviews: {
    name: 'Podcast & Interviews',
    nameZh: '播客访谈',
    icon: 'Mic',
  },
  news: {
    name: 'News',
    nameZh: '新闻资讯',
    icon: 'Newspaper',
  },
  research: {
    name: 'Research',
    nameZh: '研究论文',
    icon: 'BookOpen',
  },
};
